spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 615612093999-2a646dr6k5qv5pgbvhrdb5lug031uv95.apps.intercontinental.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - openid
              - email
              - profile
        provider:
          google:
            issuer-uri: https://accounts.google.com
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://bookingdb.c7sgwkkeg667.ap-southeast-2.rds.amazonaws.com:3306/booking_db?useSSL=false&allowPublicKeyRetrieval=true
    username: master
    password: US0m9blckS6zLzf
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  sendgrid:
    api-key: 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
    from-email: bogiaoffline@gmail.com
    template-id: d-fba2ac2ec3c643b38ae4c2956bf5fd6f
    verification-link: http://localhost:8080/api/v1/users/confirm-email

  devtools:
    add-properties: true

  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    '[org.springframework.security.oauth2]': DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: abc@123
  expiry-minutes: 60
  expiry-day: 7
  access-key: dAq3fhrpJ3a3JgJ7WxpnwoEJ8gt3Bu3CADfnKcfbwYc=
  refresh-key: SOoQytzdI6cyFJRRWSIpYJTt13UBfbA6aafbJcYRcpg=

cloudinary:
  cloud_name: dbkgbh9kl
  api_key: 847943874193696
  api_secret: Yj5APAWn75a7Jz6EmG9pCNuLUPM

redis:
  host: localhost
  port: 6379

booking:
  expiry:
    minutes: 15

momo:
  partner-code: MOMONPMB20210629
  return-url: http(s)://domain.partner.vn/redirect/
  end-point: https://test-payment.momo.vn/v2/gateway/api
  ipn-url: http(s)://domain.partner.vn/ipn/
  access-key: Q2XhhSdgpKUlQ4Ky
  secret-key: k6B53GQKSjktZGJBK2MyrDa7w9S6RyCf
  request-type: captureWallet

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: T350LZGW
    secretKey: EZVE64W4YLB6WYCPC307DMJGF5GWT6QI
    returnUrl: http://localhost:8080/api/payment/vnpay-return
    version: 2.1.0
    command: pay
    orderType: other

