spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:mysql}:${DATABASE_PORT:3306}/booking
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}

  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: bogiaoffline@gmail.com
    template-id: d-fba2ac2ec3c643b38ae4c2956bf5fd6f
    verification-link: http://localhost:8080/api/v1/users/confirm-email

  devtools:
    add-properties: true

redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}

cloudinary:
  cloud_name: dbkgbh9kl
  api_key: 847943874193696
  api_secret: Yj5APAWn75a7Jz6EmG9pCNuLUPM

jwt:
  secretKey: abc@123
  expiry-minutes: 60
  expiry-day: 7
  access-key: dAq3fhrpJ3a3JgJ7WxpnwoEJ8gt3Bu3CADfnKcfbwYc=
  refresh-key: SOoQytzdI6cyFJRRWSIpYJTt13UBfbA6aafbJcYRcpg=

booking:
  expiry:
    minutes: 15

momo:
  partner-code: MOMONPMB20210629
  return-url: http://localhost:8080/redirect/
  end-point: https://test-payment.momo.vn/v2/gateway/api
  ipn-url: http://localhost:8080/ipn/
  access-key: Q2XhhSdgpKUlQ4Ky
  secret-key: k6B53GQKSjktZGJBK2MyrDa7w9S6RyCf
  request-type: captureWallet

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: T350LZGW
    secretKey: EZVE64W4YLB6WYCPC307DMJGF5GWT6QI
    returnUrl: http://localhost:8080/api/payment/vnpay-return
    version: 2.1.0
    command: pay
    orderType: other

logging:
  level:
    root: INFO
    com.booking: INFO
